# Vars are defined in http-client.env.json and http-client.private.env.json
@agent_host={{host}}/configurable
@agent_id={{configurable_id}}

### Register the configurable agent on the theoriq protocol
POST {{theoriq_host}}/api/v1alpha2/agents
Authorization: Bearer {{biscuit}}
Content-Type: application/json

{
  "metadata": {
    "name": "Awesome Multiplication Configurable",
    "shortDescription": "Awesome Multiplication Configurable",
    "longDescription": "Awesome Multiplication",
    "tags": [
      "Math"
    ],
    "costCard": "Cost card",
    "examplePrompts": [
      "2 * 3",
      "4 * 5 * 6"
    ]
  },
  "configuration": {
    "deployment": {
      "url": "{{agent_host}}",
      "headers": []
    }
  }
}

### Configuration Schema
GET {{agent_host}}/api/v1alpha2/configuration/schema

### PublicKey
GET {{agent_host}}/api/v1alpha2/system/public-key

### Liveness
GET {{agent_host}}/api/v1alpha2/system/livez

### Unmint
POST {{theoriq_host}}/api/v1alpha2/agents/{{agent_id}}/unmint
Authorization: Bearer {{biscuit}}

### Delete
DELETE {{theoriq_host}}/api/v1alpha2/agents/{{agent_id}}
Authorization: Bearer {{biscuit}}
